spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods: '*'
            allowed-headers: '*'
            max-age: 1800
      routes:
        - id: fs
          uri: lb://cloud-fs
          predicates:
            - Path=/fs/**
          filters:
            - StripPrefix=1