spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://127.0.0.1:9000/oauth2/introspect
          client-id: cloud
          client-secret: 1234