spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://127.0.0.1:9000/oauth2/introspect
          client-id: cloud
          client-secret: 1234
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: '*'
            allowed-headers: '*'
            max-age: 1800
      routes:
        - id: auth
          uri: lb://cloud-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin,RETAIN_FIRST