spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods: '*'
            allowed-headers: '*'
            max-age: 1800