spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://127.0.0.1:9000/oauth2/introspect
          client-id: cloud
          client-secret: 1234
cloud:
  fs:
    minio:
      endpoint: http://192.168.2.2:9000
      access-key: root
      secret-key: Hj123456
      bucket: ${spring.application.name}