spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: '*'
            allowed-headers: '*'
            max-age: 1800
      routes:
        - id: fs
          uri: lb://cloud-fs
          predicates:
            - Path=/fs/**
          filters:
            - StripPrefix=1
        - id: msg
          uri: lb://cloud-msg
          predicates:
            - Path=/msg/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin,RETAIN_FIRST